"""
Processor for synthetic epidemiological data from zarr bundles.

This module handles loading synthetic data that was generated by EpiSim.jl
and processed through the synthetic generator pipeline. The synthetic data
is bundled in a single zarr file with all variables.

Synthetic data MUST use concentration mode (not total_flow) because it
contains pre-computed concentrations without flow rate information.
"""

from pathlib import Path

import numpy as np
import xarray as xr

from constants import EDAR_BIOMARKER_PREFIX, EDAR_BIOMARKER_VARIANTS

from ..config import REGION_COORD, TEMPORAL_COORD, PreprocessingConfig
from .temporal_covariates_processor import TemporalCovariatesProcessor

ZARR_ENCODING_KEYS_TO_CLEAR = {
    "chunks",
    "preferred_chunks",
    "compressors",
    "compressor",
    "filters",
    "serializer",
    "object_codec",
    "shards",
}

SYNTHETIC_ZARR_SCHEMA = {
    "required_vars": {
        "cases": ("run_id", "date", "region_id"),
        "population": ("run_id", "region_id"),
    },
    "mobility_alternatives": [
        ("mobility_time_varying", ("run_id", "origin", "destination", "date")),
        ("mobility_base", ("origin", "target")),
        ("mobility_kappa0", ("run_id", "date")),
    ],
    "edar_biomarkers": {
        f"{EDAR_BIOMARKER_PREFIX}{v}": ("run_id", "date", "edar_id")
        for v in EDAR_BIOMARKER_VARIANTS
    },
    "edar_lod": {
        f"limit_of_detection_{v}": ("run_id", "date", "edar_id")
        for v in EDAR_BIOMARKER_VARIANTS
    },
    "optional_vars": {
        "hospitalizations_raw": ("run_id", "date", "region_id"),
        "hospitalizations": ("run_id", "date", "region_id"),
        "deaths_raw": ("run_id", "date", "region_id"),
        "deaths": ("run_id", "date", "region_id"),
        "latent_S_true": ("run_id", "region_id", "date"),
        "latent_I_true": ("run_id", "region_id", "date"),
        "latent_R_true": ("run_id", "region_id", "date"),
        "latent_D_true": ("run_id", "region_id", "date"),
        "synthetic_sparsity_level": ("run_id",),
    },
}


class SyntheticProcessor:
    """
    Loads and extracts synthetic data from bundled zarr format.

    This processor handles:
    - Loading synthetic data from a single zarr bundle
    - Validating flow_mode is concentration (synthetic has no flow_rate)
    - Extracting individual data sources (cases, mobility, EDAR, population)
    - Preserving the factorized mobility format for the MobilityProcessor

    The output is a dict of xarray objects compatible with the alignment processor.
    """

    def __init__(self, config: PreprocessingConfig):
        """
        Initialize the synthetic processor.

        Args:
            config: Preprocessing configuration

        Raises:
            ValueError: If wastewater_flow_mode is not "concentration"
        """
        self.config = config

        # Synthetic data contains concentrations, not flow
        if config.wastewater_flow_mode != "concentration":
            raise ValueError(
                f"Synthetic data requires wastewater_flow_mode='concentration', "
                f"got '{config.wastewater_flow_mode}'. "
                f"Synthetic data has no flow_rate variable."
            )

    def process(
        self, synthetic_path: str, run_filter: list[str] | list[int] | None = None
    ) -> dict[str, xr.DataArray | xr.Dataset]:
        """
        Load and extract synthetic data from bundled zarr.

        Args:
            synthetic_path: Path to raw_synthetic_observations.zarr
            run_filter: Optional list of run_ids to include. If None, includes all runs.

        Returns:
            Dict with keys: cases, mobility, edar, population, temporal_covariates
        """
        self._validate_temporal_covariates_config()

        print(f"Loading synthetic data from {synthetic_path}")

        resolved_store_path = self._resolve_synthetic_store_path(synthetic_path)
        print(f"Resolved synthetic zarr group: {resolved_store_path}")

        ds = self._open_synthetic_zarr(resolved_store_path)
        print(ds)
        print()

        # Filter runs if specified
        if run_filter is not None:
            run_ids = ds["run_id"].values
            mask = np.isin(run_ids, run_filter)
            ds = ds.isel(run_id=mask)
            print(f"Filtered to {len(ds.run_id)} runs: {ds.run_id.values}")
            print()

        # Validate schema before extraction
        self._validate_schema(ds)

        synthetic_sparsity_level = None
        if "synthetic_sparsity_level" in ds:
            synthetic_sparsity_level = ds["synthetic_sparsity_level"]

        # EDAR returns tuple (flow_xr, censor_xr) for shared processing path
        edar_flow, edar_censor = self._extract_edar(ds)
        cases_data = self._extract_cases(ds)
        temporal_covariates = self._extract_temporal_covariates(
            cases_data["cases"], raw_ds=ds
        )

        result = {
            "cases": cases_data,
            "mobility": self._extract_mobility(ds),
            "edar_flow": edar_flow,  # Flow/concentration values
            "edar_censor": edar_censor,  # Censor flags
            "population": self._extract_population(ds),
            "temporal_covariates": temporal_covariates,
        }

        # Extract optional hospitalizations and deaths data
        hosp_data = self._extract_hospitalizations(ds)
        if hosp_data is not None:
            result["hospitalizations"] = hosp_data

        deaths_data = self._extract_deaths(ds)
        if deaths_data is not None:
            result["deaths"] = deaths_data

        latent_sird = self._extract_latent_sird(ds)
        if latent_sird is not None:
            result["latent_sird"] = latent_sird

        if synthetic_sparsity_level is not None:
            result["synthetic_sparsity_level"] = synthetic_sparsity_level

        return result

    def _resolve_synthetic_store_path(self, synthetic_path: str) -> str:
        """Resolve wrapper directories that contain the actual Zarr group."""
        path = Path(synthetic_path)
        if not path.exists():
            raise FileNotFoundError(f"Synthetic zarr path does not exist: {path}")

        if (path / ".zgroup").exists() or (path / ".zattrs").exists():
            return str(path)

        nested_candidates = sorted(
            child
            for child in path.iterdir()
            if child.is_dir()
            and child.suffix == ".zarr"
            and ((child / ".zgroup").exists() or (child / ".zattrs").exists())
        )
        if len(nested_candidates) == 1:
            return str(nested_candidates[0])
        if len(nested_candidates) > 1:
            raise ValueError(
                "Synthetic zarr wrapper contains multiple nested zarr groups; "
                f"cannot choose automatically: {[c.name for c in nested_candidates]}"
            )
        return str(path)

    def _open_synthetic_zarr(self, resolved_path: str) -> xr.Dataset:
        """Open synthetic zarr, handling inconsistent run_id dimensions.

        Some synthetic zarrs have variables with conflicting run_id sizes
        (e.g., LoD arrays with run_id=2 while others have run_id=8).
        This method detects such conflicts, drops the conflicting variables,
        and re-loads them with corrected coordinates.
        """
        chunks = {"run_id": self.config.run_id_chunk_size}
        try:
            ds = xr.open_zarr(
                resolved_path,
                chunks=chunks,  # type: ignore[arg-type]
            )
            self._clear_source_zarr_encodings(ds)
            return ds
        except ValueError as e:
            if "conflicting sizes" not in str(e):
                raise

            # Detect which variables have mismatched run_id sizes
            import zarr as _zarr

            store = _zarr.open(resolved_path, mode="r")
            run_id_size = None
            conflicting_vars: list[str] = []
            for name in store.array_keys():
                arr = store[name]
                dims = arr.attrs.get("_ARRAY_DIMENSIONS", [])
                if "run_id" in dims:
                    idx = dims.index("run_id")
                    size = arr.shape[idx]
                    if run_id_size is None:
                        run_id_size = size
                    elif size != run_id_size:
                        conflicting_vars.append(name)

            if not conflicting_vars:
                raise

            print(
                f"  Note: dropping {len(conflicting_vars)} variables with "
                f"conflicting run_id size: {conflicting_vars}"
            )
            ds = xr.open_zarr(
                resolved_path,
                drop_variables=conflicting_vars,
                chunks=chunks,  # type: ignore[arg-type]
            )
            self._clear_source_zarr_encodings(ds)

            # Re-add dropped LoD variables with corrected run_id coords
            if run_id_size is not None:
                run_id_coords = ds.run_id.values
                for var_name in conflicting_vars:
                    arr = store[var_name]
                    dims = arr.attrs.get("_ARRAY_DIMENSIONS", [])
                    data = np.array(arr)

                    # Broadcast along run_id to match the main dataset
                    if "run_id" in dims and data.shape[0] != len(run_id_coords):
                        data = np.broadcast_to(
                            data[0:1],
                            (len(run_id_coords),) + data.shape[1:],
                        ).copy()

                    da = xr.DataArray(
                        data,
                        dims=dims,
                        coords={
                            d: ds.coords[d].values
                            if d in ds.coords
                            else np.arange(s)
                            for d, s in zip(dims, data.shape)
                        },
                        name=var_name,
                    )
                    ds[var_name] = da

            print(ds)
            print()
            return ds

    def _clear_source_zarr_encodings(self, dataset: xr.Dataset) -> None:
        """Remove inherited source chunk/compressor encodings from opened Zarr vars."""
        for var_name in dataset.data_vars:
            var = dataset[var_name]
            for key in ZARR_ENCODING_KEYS_TO_CLEAR:
                var.encoding.pop(key, None)

        for coord_name in dataset.coords:
            coord = dataset.coords[coord_name]
            for key in ZARR_ENCODING_KEYS_TO_CLEAR:
                coord.encoding.pop(key, None)

    def _validate_schema(self, ds: xr.Dataset) -> None:
        """Validate dataset against SYNTHETIC_ZARR_SCHEMA before extraction.

        Checks required variables, mobility formats, EDAR biomarker/LoD pairs,
        and warns for missing optional variables. Raises ValueError with all
        failures listed at once.
        """
        errors: list[str] = []

        # Required variables
        for var_name, expected_dims in SYNTHETIC_ZARR_SCHEMA["required_vars"].items():
            if var_name not in ds:
                errors.append(f"Missing required variable: '{var_name}'")
            elif set(ds[var_name].dims) != set(expected_dims):
                errors.append(
                    f"Variable '{var_name}' has dims {ds[var_name].dims}, "
                    f"expected {expected_dims}"
                )

        # Mobility: at least one format must be present
        mobility_ok = False
        for var_name, expected_dims in SYNTHETIC_ZARR_SCHEMA["mobility_alternatives"]:
            if var_name in ds:
                if set(ds[var_name].dims) == set(expected_dims):
                    mobility_ok = True
                    break
        if not mobility_ok:
            errors.append(
                "No valid mobility format found. Expected either "
                "'mobility_time_varying' with dims (run_id, origin, destination, date) "
                "or 'mobility_base' + 'mobility_kappa0' with dims "
                "(origin, target) and (run_id, date)."
            )

        # EDAR biomarkers + LoD
        for var_name, expected_dims in SYNTHETIC_ZARR_SCHEMA["edar_biomarkers"].items():
            if var_name not in ds:
                errors.append(f"Missing EDAR biomarker variable: '{var_name}'")
            elif set(ds[var_name].dims) != set(expected_dims):
                errors.append(
                    f"Biomarker '{var_name}' has dims {ds[var_name].dims}, "
                    f"expected {expected_dims}"
                )

        for var_name, expected_dims in SYNTHETIC_ZARR_SCHEMA["edar_lod"].items():
            if var_name not in ds:
                errors.append(f"Missing EDAR LoD variable: '{var_name}'")
            elif set(ds[var_name].dims) != set(expected_dims):
                errors.append(
                    f"LoD '{var_name}' has dims {ds[var_name].dims}, "
                    f"expected {expected_dims}"
                )

        if errors:
            raise ValueError(
                "Synthetic zarr schema validation failed:\n"
                + "\n".join(f"  - {e}" for e in errors)
            )

        # Optional variables (warn only)
        for var_name in SYNTHETIC_ZARR_SCHEMA["optional_vars"]:
            if var_name not in ds:
                print(f"  Note: optional variable '{var_name}' not present")

        if "synthetic_sparsity_level" in ds:
            sparsity = ds["synthetic_sparsity_level"]
            print(
                "  ✓ Found synthetic_sparsity_level metadata: "
                f"{sparsity.shape}"
            )
        else:
            print(
                "Warning: synthetic_sparsity_level not found; "
                "curriculum sparsity filtering will be unavailable."
            )

    def _select_optional_observed_series(
        self,
        ds: xr.Dataset,
        *,
        channel_name: str,
        candidate_vars: list[str],
    ) -> xr.DataArray | None:
        """Pick an observed channel, ignoring any *_true evaluation series."""
        required_dims = {"run_id", TEMPORAL_COORD, REGION_COORD}

        for var_name in candidate_vars:
            if var_name not in ds:
                continue
            candidate = ds[var_name]
            if set(candidate.dims) != required_dims:
                print(
                    f"  Warning: '{var_name}' has unexpected dims {candidate.dims}; "
                    "skipping this candidate."
                )
                continue

            candidate = candidate.transpose("run_id", TEMPORAL_COORD, REGION_COORD)
            if var_name != channel_name:
                print(f"  Using observed channel '{var_name}' for '{channel_name}'.")
            return candidate

        if f"{channel_name}_true" in ds:
            print(
                f"  Note: '{channel_name}_true' is available but ignored "
                "(ground truth is evaluation-only)."
            )
        print(f"  No observed {channel_name} channel found; skipping.")
        return None

    def _validate_temporal_covariates_config(self) -> None:
        """Enforce temporal covariates in synthetic preprocessing."""
        if self.config.temporal_covariates is None:
            raise ValueError(
                "Synthetic preprocessing requires temporal_covariates configuration. "
                "Add a `temporal_covariates` block with `include_day_of_week`, "
                "`include_holidays`, and `holiday_calendar_file`."
            )

    def _extract_temporal_covariates(
        self, cases: xr.DataArray, raw_ds: xr.Dataset | None = None
    ) -> xr.DataArray:
        """Generate temporal covariates aligned to filtered dates.

        When ``include_lockdown_severity`` is enabled and the raw synthetic
        zarr contains ``mobility_kappa0``, the continuous κ₀ values are
        bucketed into an ordinal 0–3 lockdown severity channel and the
        output is promoted to ``(run_id, date, covariate)`` so each
        synthetic scenario carries its own NPI profile.  Downstream
        run-filtering squeezes singleton run_ids, so consumption code
        needs no changes.

        κ₀ bucketing:
            0   → 0  (no lockdown)
            (0, 0.2] → 1  (mild)
            (0.2, 0.5] → 2  (moderate)
            > 0.5 → 3  (strict)
        """
        if cases.sizes[TEMPORAL_COORD] == 0:
            raise ValueError("No dates available to generate temporal covariates")

        tc_cfg = self.config.temporal_covariates
        use_kappa_lockdown = (
            tc_cfg is not None
            and tc_cfg.include_lockdown_severity
            and raw_ds is not None
            and "mobility_kappa0" in raw_ds
        )

        # Build base calendar covariates via TemporalCovariatesProcessor.
        # Temporarily disable lockdown_severity so the processor only emits
        # calendar features (dow, holidays); the synthetic lockdown channel
        # is derived from kappa0 instead.
        if use_kappa_lockdown:
            saved_lockdown = tc_cfg.include_lockdown_severity
            tc_cfg.include_lockdown_severity = False

        processor = TemporalCovariatesProcessor(self.config)
        temporal_covariates = processor.process(
            start_date=cases[TEMPORAL_COORD].values[0],
            end_date=cases[TEMPORAL_COORD].values[-1],
        )
        target_dates = cases[TEMPORAL_COORD].values
        if not np.array_equal(
            temporal_covariates[TEMPORAL_COORD].values,
            target_dates,
        ):
            temporal_covariates = temporal_covariates.reindex(
                {TEMPORAL_COORD: target_dates}
            )

        if use_kappa_lockdown:
            tc_cfg.include_lockdown_severity = saved_lockdown
            temporal_covariates = self._inject_kappa0_lockdown(
                temporal_covariates, raw_ds
            )

        print("  ✓ Added temporal covariates to synthetic payload")
        return temporal_covariates

    def _inject_kappa0_lockdown(
        self, base_covariates: xr.DataArray, raw_ds: xr.Dataset
    ) -> xr.DataArray:
        """Bucket mobility_kappa0 into ordinal lockdown severity and merge.

        Args:
            base_covariates: Calendar covariates with dims (date, covariate).
            raw_ds: Raw synthetic zarr containing ``mobility_kappa0``.

        Returns:
            DataArray with dims (run_id, date, covariate) where the last
            covariate is ``"lockdown_severity"`` derived from bucketed κ₀.
        """
        kappa0 = raw_ds["mobility_kappa0"]  # (run_id, date)

        # Filter to target date range
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)
        time_mask = (kappa0[TEMPORAL_COORD] >= start_date) & (
            kappa0[TEMPORAL_COORD] <= end_date
        )
        kappa0_filtered = kappa0.isel({TEMPORAL_COORD: time_mask})

        # Reindex to exact target dates (in case of gaps)
        target_dates = base_covariates[TEMPORAL_COORD].values
        kappa0_aligned = kappa0_filtered.reindex(
            {TEMPORAL_COORD: target_dates}, fill_value=0.0
        )

        # Bucket: 0→0, (0,0.2]→1, (0.2,0.5]→2, >0.5→3
        kappa0_np = kappa0_aligned.values  # (run_id, date)
        bucketed = np.digitize(kappa0_np, bins=[0.0, 0.2, 0.5]).astype(np.float32)

        # Build lockdown severity DataArray (run_id, date, 1)
        lockdown_da = xr.DataArray(
            bucketed[:, :, np.newaxis],
            dims=["run_id", TEMPORAL_COORD, "covariate"],
            coords={
                "run_id": kappa0_aligned.run_id.values,
                TEMPORAL_COORD: target_dates,
                "covariate": ["lockdown_severity"],
            },
        )

        # Broadcast base covariates (date, covariate) → (run_id, date, covariate)
        run_ids = kappa0_aligned.run_id.values
        base_broadcast = base_covariates.expand_dims(
            {"run_id": run_ids}, axis=0
        )

        # Concatenate along covariate dim
        result = xr.concat(
            [base_broadcast, lockdown_da], dim="covariate"
        )
        result.name = "temporal_covariates"

        print(
            f"  ✓ Injected lockdown severity from mobility_kappa0: "
            f"{len(run_ids)} runs, buckets={np.unique(bucketed).tolist()}"
        )
        return result

    def _extract_cases(self, ds: xr.Dataset) -> xr.Dataset:
        """Extract cases data from synthetic bundle.

        Expected shape: (run_id, date, region_id)
        Preserves run_id dimension for curriculum training.
        Extracts cases, computes cases_mask from notnull(), computes cases_age from mask.
        """
        print("Extracting cases...")

        # Required variables for clinical series preprocessing
        if "cases" not in ds:
            available = list(ds.data_vars.keys())
            raise KeyError(
                f"Required variable 'cases' not found in synthetic dataset. "
                f"Available variables: {available}"
            )

        # Cases: (run_id, date, region_id) → preserve run_id dimension
        cases = ds["cases"]

        # Verify temporal dimension matches config
        cases = cases.rename({TEMPORAL_COORD: TEMPORAL_COORD})

        # Crop to config date range (applies to all runs)
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)

        time_mask = (cases[TEMPORAL_COORD] >= start_date) & (
            cases[TEMPORAL_COORD] <= end_date
        )
        cases_filtered = cases.isel({TEMPORAL_COORD: time_mask})

        assert not cases_filtered.sizes[TEMPORAL_COORD] == 0, (
            "No cases data in temporal range"
        )

        # Compute mask from notnull(): True where observed, False where missing
        cases_mask_filtered = cases_filtered.notnull()

        # Compute age channel from mask: days since last observation
        # Age formula: current_time - last_seen_time + 1 (so observation day has age=1)
        # Max age is 14 (indicates no prior observation within window)
        cases_age_filtered = self._compute_age_from_mask(cases_mask_filtered)

        num_runs = len(cases_filtered.run_id)
        print(f"  ✓ Extracted cases with {num_runs} runs: {cases_filtered.shape}")

        # Return dataset with all three required variables
        return xr.Dataset(
            {
                "cases": cases_filtered,
                "cases_mask": cases_mask_filtered,
                "cases_age": cases_age_filtered,
            }
        )

    def _compute_age_from_mask(self, mask: xr.DataArray) -> xr.DataArray:
        """Compute age channel from observation mask.

        Age represents days since last observation (1-14).
        Age 1 means observed on current day.
        Age 14 means no observation within the last 14 days.

        Args:
            mask: Boolean mask DataArray with dims (run_id, date, region_id)
                  True indicates observed, False indicates missing.

        Returns:
            Age DataArray with same dims as mask, values 1-14.
        """
        # Convert mask to numpy for computation
        mask_values = mask.values  # shape: (run_id, date, region_id)
        age_values = np.full(mask_values.shape, 14, dtype=np.uint8)

        # Iterate over runs and regions
        for run_idx in range(mask_values.shape[0]):
            for region_idx in range(mask_values.shape[2]):
                mask_1d = mask_values[run_idx, :, region_idx]
                last_seen = None
                for t in range(len(mask_1d)):
                    if mask_1d[t]:
                        last_seen = t
                        age_values[run_idx, t, region_idx] = 1
                    elif last_seen is not None:
                        age_values[run_idx, t, region_idx] = min(t - last_seen + 1, 14)

        # Create DataArray with same coords as mask
        age_da = xr.DataArray(
            age_values,
            dims=mask.dims,
            coords=mask.coords,
            name="cases_age",
        )

        return age_da

    def _extract_mobility(self, ds: xr.Dataset) -> xr.Dataset:
        """Extract mobility data from synthetic dataset.

        Supports two formats:
        1. New: mobility_time_varying (pre-computed with kappa0 applied)
        2. Legacy: mobility_base + mobility_kappa0 (factorized format)

        Preserves run_id dimension.
        Returns dataset with dimensions (run_id, date, origin, destination).
        """
        print("Extracting mobility...")

        # Check for time-varying format (new synthetic data)
        if "mobility_time_varying" in ds:
            print("  Found mobility_time_varying (pre-computed format)")
            mobility = ds["mobility_time_varying"]

            # Transpose to match expected dimension order: (run_id, date, origin, destination)
            # Input dims: (run_id, origin, target, date)
            mobility = mobility.transpose("run_id", TEMPORAL_COORD, "origin", "target")
            mobility = mobility.rename({"target": "destination"})

            # Filter by date range
            start_date = np.datetime64(self.config.start_date)
            end_date = np.datetime64(self.config.end_date)
            time_mask = (mobility[TEMPORAL_COORD] >= start_date) & (
                mobility[TEMPORAL_COORD] <= end_date
            )
            mobility_filtered = mobility.isel({TEMPORAL_COORD: time_mask})

            num_runs = len(mobility_filtered.run_id)
            print(
                f"  ✓ Extracted mobility with {num_runs} runs: {mobility_filtered.shape}"
            )
            return mobility_filtered.to_dataset(name="mobility")

        # Fall back to factorized format (legacy synthetic data)
        print("  Using factorized format (mobility_base + mobility_kappa0)")

        mobility_base = ds["mobility_base"]  # (origin, target)
        mobility_kappa0 = ds["mobility_kappa0"]  # (run_id, date)

        # Rename to match expected coords
        mobility_base = mobility_base.rename(
            {"origin": REGION_COORD, "target": "destination"}
        )
        mobility_base = mobility_base.rename({REGION_COORD: "origin"})

        # Filter by date range (applies to all runs)
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)

        time_mask = (mobility_kappa0[TEMPORAL_COORD] >= start_date) & (
            mobility_kappa0[TEMPORAL_COORD] <= end_date
        )
        kappa0_filtered = mobility_kappa0.isel({TEMPORAL_COORD: time_mask})

        # Reconstruct mobility tensor: mobility[run_id, date, origin, destination]
        # Using formula: mobility[date] = mobility_base * (1 - kappa0[date])
        # Use xarray broadcasting to preserve dask chunking
        reduction_factor = 1.0 - kappa0_filtered  # (run_id, date)

        # Expand dims with actual coordinate values for proper alignment
        # reduction_factor: (run_id, date) -> (run_id, date, origin, destination)
        reduction_factor_expanded = reduction_factor.expand_dims(
            {
                "origin": mobility_base["origin"].values,
                "destination": mobility_base["destination"].values,
            }
        )

        # mobility_base: (origin, destination) -> broadcast to (run_id, date, origin, destination)
        mobility_reconstructed = mobility_base * reduction_factor_expanded

        # Reorder dimensions to (run_id, date, origin, destination)
        mobility_reconstructed = mobility_reconstructed.transpose(
            "run_id", TEMPORAL_COORD, "origin", "destination"
        )

        mobility_ds = mobility_reconstructed.to_dataset(name="mobility")

        num_runs = len(mobility_reconstructed.run_id)
        print(
            f"  ✓ Reconstructed mobility tensor with {num_runs} runs: {mobility_reconstructed.shape}"
        )
        return mobility_ds

    def _extract_edar(self, ds: xr.Dataset) -> tuple[xr.DataArray, xr.DataArray]:
        """
        Extract EDAR biomarker data in the same intermediate format as real data.

        Preserves run_id dimension.

        Expected variables (validated by _validate_schema):
        - edar_biomarker_N1, N2, IP4: (run_id, date, edar_id)
        - limit_of_detection_N1, N2, IP4: (run_id, date, edar_id)

        Returns:
            Tuple of (flow_xr, censor_xr) with dimensions (run_id, date, edar_id, variant)
            Compatible with EDARProcessor.process_from_xarray()
        """
        print("Extracting EDAR biomarkers...")

        flow_list = []
        censor_list = []

        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)

        for variant in EDAR_BIOMARKER_VARIANTS:
            var_name = f"{EDAR_BIOMARKER_PREFIX}{variant}"
            lod_name = f"limit_of_detection_{variant}"

            biomarker = ds[var_name]
            lod = ds[lod_name]

            # Filter both biomarker and LoD by date range
            time_mask = (biomarker[TEMPORAL_COORD] >= start_date) & (
                biomarker[TEMPORAL_COORD] <= end_date
            )
            biomarker_filtered = biomarker.isel({TEMPORAL_COORD: time_mask})
            lod_filtered = lod.isel({TEMPORAL_COORD: time_mask})

            # Compute censor flag: 1.0 if value <= LoD, else 0.0 (for finite values only)
            censor = xr.where(
                (biomarker_filtered <= lod_filtered) & biomarker_filtered.notnull(),
                1.0,
                0.0,
            ).fillna(0.0)

            flow_list.append(biomarker_filtered)
            censor_list.append(censor)

        if not flow_list:
            raise ValueError("No EDAR biomarker data found in synthetic dataset")

        # Stack into (run_id, date, edar_id, variant) format
        flow_xr = xr.concat(flow_list, dim="variant").assign_coords(
            variant=EDAR_BIOMARKER_VARIANTS[: len(flow_list)]
        )
        censor_xr = xr.concat(censor_list, dim="variant").assign_coords(
            variant=EDAR_BIOMARKER_VARIANTS[: len(censor_list)]
        )

        num_runs = len(flow_xr.run_id)
        print(f"  ✓ Extracted {len(flow_list)} biomarker variants with {num_runs} runs")
        return flow_xr, censor_xr

    def _extract_population(self, ds: xr.Dataset) -> xr.DataArray:
        """Extract population data.

        Preserves run_id dimension.

        Expected: (run_id, region_id)
        """
        print("Extracting population...")

        pop = ds["population"]  # (run_id, region_id)

        # Verify region coord matches
        pop = pop.rename({"region_id": REGION_COORD})

        num_runs = len(pop.run_id)
        print(f"  ✓ Extracted population with {num_runs} runs: {pop.shape}")
        return pop

    def _extract_latent_sird(self, ds: xr.Dataset) -> xr.Dataset | None:
        """Extract latent SIRD compartments normalized to fraction space."""
        latent_names = (
            "latent_S_true",
            "latent_I_true",
            "latent_R_true",
            "latent_D_true",
        )
        missing = [name for name in latent_names if name not in ds]
        if missing:
            print(
                "  Warning: latent SIRD variables missing from synthetic dataset; "
                f"skipping latent supervision targets: {missing}"
            )
            return None

        if "population" not in ds:
            print(
                "  Warning: population missing from synthetic dataset; "
                "skipping latent supervision targets."
            )
            return None

        print("Extracting latent SIRD targets...")
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)
        population = ds["population"].rename({"region_id": REGION_COORD}).astype(
            np.float32
        )
        population = population.where(population > 0)
        latent_vars: dict[str, xr.DataArray] = {}

        for name in latent_names:
            latent = ds[name].transpose("run_id", TEMPORAL_COORD, REGION_COORD)
            time_mask = (latent[TEMPORAL_COORD] >= start_date) & (
                latent[TEMPORAL_COORD] <= end_date
            )
            latent = latent.isel({TEMPORAL_COORD: time_mask}).astype(np.float32)

            # The model roll-forward runs in fraction space with N=1.0, so
            # normalize raw synthetic counts by population during preprocessing.
            latent_fraction = (latent / population).astype(np.float32)
            latent_mask = latent_fraction.notnull()

            latent_vars[name] = latent_fraction
            latent_vars[f"{name}_mask"] = latent_mask

        num_runs = len(ds.run_id)
        example_name = latent_names[0]
        print(
            "  ✓ Extracted latent SIRD targets with "
            f"{num_runs} runs: {latent_vars[example_name].shape}"
        )
        return xr.Dataset(latent_vars)

    def _extract_hospitalizations(self, ds: xr.Dataset) -> xr.Dataset | None:
        """Extract hospitalizations data from synthetic bundle.

        Expected shape: (run_id, date, region_id)
        Preserves run_id dimension for curriculum training.

        Returns None if hospitalizations not present in synthetic data.
        """
        hosp = self._select_optional_observed_series(
            ds,
            channel_name="hospitalizations",
            candidate_vars=["hospitalizations_raw", "hospitalizations"],
        )
        if hosp is None:
            return None

        print("Extracting hospitalizations...")

        # Crop to config date range (applies to all runs)
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)

        time_mask = (hosp[TEMPORAL_COORD] >= start_date) & (
            hosp[TEMPORAL_COORD] <= end_date
        )
        hosp_filtered = hosp.isel({TEMPORAL_COORD: time_mask})

        if hosp_filtered.sizes[TEMPORAL_COORD] == 0:
            print("  Warning: No hospitalizations data in temporal range")
            return None

        # Create mask and age channels matching EDAR conventions
        # Mask: True if data available, False if missing/NaN
        hosp_mask = hosp_filtered.notnull()

        # Age: Days since last measurement (computed from mask)
        hosp_age = self._compute_age_from_mask(hosp_mask)

        num_runs = len(hosp_filtered.run_id)
        print(
            f"  ✓ Extracted hospitalizations with {num_runs} runs: {hosp_filtered.shape}"
        )

        return xr.Dataset(
            {
                "hospitalizations": hosp_filtered,
                "hospitalizations_mask": hosp_mask,
                "hospitalizations_age": hosp_age,
            }
        )

    def _extract_deaths(self, ds: xr.Dataset) -> xr.Dataset | None:
        """Extract deaths data from synthetic bundle.

        Expected shape: (run_id, date, region_id)
        Preserves run_id dimension for curriculum training.

        Returns None if deaths not present in synthetic data.
        """
        deaths = self._select_optional_observed_series(
            ds,
            channel_name="deaths",
            candidate_vars=["deaths_raw", "deaths"],
        )
        if deaths is None:
            return None

        print("Extracting deaths...")

        # Crop to config date range (applies to all runs)
        start_date = np.datetime64(self.config.start_date)
        end_date = np.datetime64(self.config.end_date)

        time_mask = (deaths[TEMPORAL_COORD] >= start_date) & (
            deaths[TEMPORAL_COORD] <= end_date
        )
        deaths_filtered = deaths.isel({TEMPORAL_COORD: time_mask})

        if deaths_filtered.sizes[TEMPORAL_COORD] == 0:
            print("  Warning: No deaths data in temporal range")
            return None

        # Create mask and age channels matching EDAR conventions
        # Mask: True if data available, False if missing/NaN
        deaths_mask = deaths_filtered.notnull()

        # Age: Days since last measurement (computed from mask)
        deaths_age = self._compute_age_from_mask(deaths_mask)

        num_runs = len(deaths_filtered.run_id)
        print(f"  ✓ Extracted deaths with {num_runs} runs: {deaths_filtered.shape}")

        return xr.Dataset(
            {
                "deaths": deaths_filtered,
                "deaths_mask": deaths_mask,
                "deaths_age": deaths_age,
            }
        )
